version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auctions
      - item
      - bids
    ports:
      - "4000:4000"

  vault_dev:
    image: hashicorp/vault:latest
    restart: 
      on-failure:10
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8201'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address":"0.0.0.0:8201","tls_disable":"0", "tls_cert_file":"/data/cert.pem","tls_key_file":"/data/key.pem"}}],"default_lease_ttl": "168h","max_lease_ttl": "720h"}, "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-volume:/data
    healthcheck:
      retries: 5
    command: server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - default

  auth:
    image: braunerr/authservice:latest-dev
    container_name: auth
    environment:
      - MongoDbConnectionString=mongodb+srv://GroenOlsen:BhvQmiihJWiurl2V@auktionshusgo.yzctdhc.mongodb.net/?retryWrites=true&w=majority
      - Secret=266BABE7C9DB9A34A7EB26E867FB2CA8833303E2CE6AAF28F6DDF04950718141
      - Issuer=issuer
    expose:
      - "80"
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  bids:
    image: braunerr/bidservice:latest-dev
    container_name: bids
    environment:
      - HostnameRabbit=rabbitmq-dev
      - MongoDbConnectionString=mongodb+srv://GroenOlsen:BhvQmiihJWiurl2V@auktionshusgo.yzctdhc.mongodb.net/?retryWrites=true&w=majority
      - Secret=266BABE7C9DB9A34A7EB26E867FB2CA8833303E2CE6AAF28F6DDF04950718141
      - Issuer=issuer
    expose:
      - "80"
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  item:
    image: braunerr/itemservice:latest-dev
    container_name: items
    environment:
      - HostnameRabbit=rabbitmq-dev
      - MongoDbConnectionString=mongodb+srv://GroenOlsen:BhvQmiihJWiurl2V@auktionshusgo.yzctdhc.mongodb.net/?retryWrites=true&w=majority
      - Secret=266BABE7C9DB9A34A7EB26E867FB2CA8833303E2CE6AAF28F6DDF04950718141
      - Issuer=issuer  
    expose:
      - "80"
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  auctions:
    image: braunerr/auctionservice:latest-dev
    container_name: auctions
    environment:
      - HostnameRabbit=rabbitmq-dev
      - MongoDbConnectionString=mongodb+srv://GroenOlsen:BhvQmiihJWiurl2V@auktionshusgo.yzctdhc.mongodb.net/?retryWrites=true&w=majority
      - Secret=266BABE7C9DB9A34A7EB26E867FB2CA8833303E2CE6AAF28F6DDF04950718141
      - Issuer=issuer    
    expose:
      - "80"
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  users:
    image: braunerr/userservice:latest-dev
    container_name: users
    environment:
      - HostnameRabbit=rabbitmq-dev
    expose:
      - "80"
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    image: braunerr/service-worker:latest-dev
    container_name: worker
    environment:
      - HostnameRabbit=rabbitmq-dev
      - MongoDbConnectionString=mongodb+srv://GroenOlsen:BhvQmiihJWiurl2V@auktionshusgo.yzctdhc.mongodb.net/?retryWrites=true&w=majority
    expose:
      - "80"
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:management
    hostname: "rabbitmq-dev"

    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  default:
    driver: bridge
