version: '3.9'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - default

  auth:
    image: braunerr/authservice:latest-dev
    container_name: auth
    environment:
      - Secret=secret
      - Issuer=issuer
    ports:
      - "8002:80"
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  auctions:
    image: braunerr/auctionservice:latest-dev
    container_name: auctions
    environment:
      - HostnameRabbit=rabbitmq-dev
    ports:
      - "8001:80"
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    image: braunerr/service-worker:latest-dev
    container_name: worker
    environment:
      - HostnameRabbit=rabbitmq-dev
    ports:
      - "8000:80"
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:management
    hostname: "rabbitmq-dev"
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
    mongodb_data_container:
    images_data:
        external: false
networks:
  default:
    driver: bridge